/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#4c3910",
        "on-surface-variant": "#4e4539",
        "on-error": "#ffffff",
        "primary-container": "#c59d5f",
        surface: "#f6efe3",
        secondary: "#9f402d",
        "surface-container-highest": "#e4e2dd",
        "on-primary-fixed": "#281800",
        "on-primary-container": "#4f3400",
        "secondary-fixed-dim": "#ffb4a5",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "surface-container": "#f0eee9",
        "surface-dim": "#dbdad5",
        "inverse-primary": "#ebc07e",
        "primary-fixed-dim": "#ebc07e",
        "on-tertiary-container": "#1f3b5e",
        "on-background": "#1b1c19",
        "primary-fixed": "#ffddae",
        background: "#f6efe3",
        "surface-container-low": "#f5f3ee",
        "surface-bright": "#fbf9f4",
        "inverse-on-surface": "#f2f1ec",
        "tertiary-fixed-dim": "#aec8f3",
        "tertiary-container": "#8ba5ce",
        tertiary: "#465f85",
        "secondary-fixed": "#ffdad3",
        "on-secondary-fixed-variant": "#802918",
        "error-container": "#ffdad6",
        "surface-container-high": "#eae8e3",
        "on-surface": "#1b1c19",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#d4e3ff",
        outline: "#807568",
        "on-secondary-container": "#732010",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#5e410b",
        "surface-tint": "#795921",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "outline-variant": "#d2c4b5",
        "on-tertiary-fixed-variant": "#2d486c",
        "on-secondary-fixed": "#3e0500",
        "inverse-surface": "#30312e",
        "surface-variant": "#e4e2dd",
        "on-tertiary-fixed": "#001c3a",
        "secondary-container": "#fd876f",
        "accent-gold": "#f0cf5a",
        "deep-green": "#59814c",
        "brown": "#4c3910",
        "gold": "#f0cf5a",
        "sage": "#59814c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "paragraph-gap": "24px",
        "max-reading-width": "780px",
        "base-unit": "8px",
        "section-gap": "80px",
        "margin-mobile": "20px",
        gutter: "24px",
      },
      fontFamily: {
        display: ["Fraunces", "serif"],
        body: ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-md": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-sm": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        caption: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "pull-quote": ["28px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
